TRUNCATE TABLE  userprofilemaster ; 
TRUNCATE TABLE  optionsmaster;
TRUNCATE TABLE  devopspracticesmaster ;
TRUNCATE TABLE  displaycategoriesmaster ;
TRUNCATE TABLE  questionsmaster ;
TRUNCATE TABLE  evaluationsmaster ;
TRUNCATE TABLE  levelsrecommendationsmaster ;


	/*USER PROFILE MASTER DATABASE*/

INSERT INTO `dmat`.`userprofilemaster` (`question`, `option1`, `option2`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('What are the business drivers for this project ? Also, describe the outcome that the project is expected to achieve.', null, null, null, CURRENT_TIMESTAMP(), null, 'manual', 'active');
INSERT INTO `dmat`.`userprofilemaster` (`question`, `option1`, `option2`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('What is the nature of work being undertaken in the project?', 'L1/L2 support', 'Feature Creation/Enhancement', 'L1/L2 support - On call support', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`userprofilemaster` (`question`, `option1`, `option2`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('Do you follow Agile methodology in your project?', 'Yes', 'No', 'While you take this assessment please take a holistic approach for the work that is being done. The work may be done by Customer or Persistent, however look at the assessment with the view point of how the program goals can be achieved.', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`userprofilemaster` (`question`, `option1`, `option2`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('Please mention technologies used in the project.', null, null,'ex. Java, HTML, Python', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`userprofilemaster` (`question`, `option1`, `option2`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('Please mention the current tools used in the project.', null, null, 'ex. Junit, Nunit, Jira etc.', NOW(), null, 'manual', 'active');	
INSERT INTO `dmat`.`userprofilemaster` (`question`, `option1`, `option2`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('Email IDs of all people who were available during this assessment:', null, null, null, NOW(), null, 'manual', 'active');	
	


/* DevOps Practice Master Data*/
INSERT INTO `dmat`.`devopspracticesmaster` (`name`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('Continual Integration', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`devopspracticesmaster` (`name`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('Continual Testing', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`devopspracticesmaster` (`name`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('Continual learning', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`devopspracticesmaster` (`name`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('Continual Deployment', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`devopspracticesmaster` (`name`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('Mindset', NOW(), null, 'manual', 'active');
	


/* Display Category Master Data */
INSERT INTO `dmat`.`displaycategoriesmaster` (`name`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`,`maxscore`) VALUES ('Process', NOW(), null, 'manual', 'active',5);
INSERT INTO `dmat`.`displaycategoriesmaster` (`name`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`,`maxscore`) VALUES ('Technology', NOW(), null, 'manual', 'active',5);
INSERT INTO `dmat`.`displaycategoriesmaster` (`name`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`,`maxscore`) VALUES ('People', NOW(), null, 'manual', 'active',5);
INSERT INTO `dmat`.`displaycategoriesmaster` (`name`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`,`maxscore`) VALUES ('Measurement', NOW(), null, 'manual', 'active',5);
INSERT INTO `dmat`.`displaycategoriesmaster` (`name`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`,`maxscore`) VALUES ('Outcome', NOW(), null, 'manual', 'active',6);
	



/* Questions Master Data*/

alter table `dmat`.`questionsmaster` modify `question` varchar(1000);


/*process*/
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How do you plan, prioritize and schedule work?',0, '1', '1', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`,`devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How does your backlog take business impact into account?',0, '3', '1', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How do you plan and measure engineering improvements?',0, '3', '1', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`,`devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('What is your approach to Work In Process (WIP)?', 0 ,'3', '1', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How do you manage (non-code) dependencies between internal teams?', 0,'4', '1', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How do you manage suppliers for outsourced development?',0, '3', '1', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('Who has access to your production environments?',0, '4', '1', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`,`devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How do you rate understanding about product / application requirements within the team?',0, '3', '1', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How are releases in the project approved ?',0, '4', '1', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How do development and operations teams collaborate during a production issue?', 0,'1', '1', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How do you improve your process?',0, '3', '1', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`,`devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`,`reason`) VALUES ('What are your security practices? ( If you choose "Option e" please explain why so) ',0, '1', '1', null, NOW(), null, 'manual', 'active','please enter');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('What are your policies around open source software?',0, '1', '1', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('What is your Definition of Done?',0, '3', '1', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('What is your Definition of Ready?',0, '3', '1', null, NOW(), null, 'manual', 'active');



/*technology*/
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('What files do you keep under version control?', 0,'1', '2', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('What is your branching policy?',0, '1', '2', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How do you review code changes?',0, '1', '2', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How do you manage code dependencies across teams which share the same code base as your project?',0, '1', '2', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How do code changes get built? ',0, '1', '2', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How do you manage environments in dev, test and production?',0, '4', '2', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How do you roll out new features to end users?',0, '4', '2', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('What is your policy for using the public cloud?',0, '4', '2', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How do you manage access control in terms of password management, storing of credentials or other policies?',0, '4', '2', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('What testing do you automate?',0, '2', '2', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How do you make sure that code is maintainable and reliable?',0, '3', '2', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('What does your team consider good testing?',0, '2', '2', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('When do you test for security?',0, '2', '2', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How do you test mobile apps?',0, '2', '2', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('What instrumentation do you use to monitor applications running in production?', 0,'3', '2', null, NOW(), null, 'manual', 'active');



/*people*/
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('Who makes decisions in the organization?', 0 ,'3', '3', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How does your team collaborate, share risks, innovate, and learn?', 0,'3', '3', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('When corporate governance discovers that a lack of systematic approach/some mistake commited has resulted into project failure what happens?',0, '3', '3', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How does your organization handles failures of project and people?',0, '3', '3', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('What are the mechanism to upgrade knowledge in the areas of software engineering, project / program management, problem solving and automation?',0,'3', '3', null, NOW(), null, 'manual', 'active');



/*measurement*/
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How do you measure code quality?',0, '3', '4', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('What decisions do you make by looking at usage data from your applications?',0, '3', '4', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How do you gather and measure feedback from end users?',0,'3', '4', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How do you get the information about health of application in operations?',0, '3', '4', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How do you use metric data for the purpose of decision making?', 0,'3', '4', null, NOW(), null, 'manual', 'active');



/*outcome*/
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('For the application or service you work on, how often does your organization deploy code to production?',0, '4', '5', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('What is your lead time for changes (i.e., how long does it take to go from \"code committed\" to \"code successfully running in production\")?',0, '4', '5', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`,`devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How long does it generally take to restore service when a service incident occurs (e.g., unplanned outage, service impairment, etc.)?',0,'4', '5', null, NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('When you deploy a change to the primary application or service you work on, what percentage of the changes result in degraded service or subsequently require remediation?', 0,'3', '5', null, NOW(), null, 'manual', 'active');


INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How long does it take for the product management team to provide the engineering team with an updated set of requirements when customer feedback indicates that the released content needs to be modified? ',1,'3','5',null,NOW(),null,'manual','active');

INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How quickly can a line of code once changed be delivered to the hands of the customer after being fully tested? ',1,'3','5',null,NOW(),null,'manual','active');

INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('What is the manual cost of executing a fully functional regression test suite?(Note:Fully automated test cases have zero manual cost)?For ex:Your team requires 4 people spending 2-4 days to do regression testing.Best case = 8 man-days,worst case = 16 man-days, average = 12 man-days? ',1,'3','5',null,NOW(),null,'manual','active');

INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How long would it take for developers to find out that their committed source code change broke a critical or commonly used function?For ex:Your team makes a release every month with 2 weeks of development,continuous integration builds which takes an hour,followed by 1 week of regression testing.In the best case,problem is found during CI build in 1 hour.In the worst case,problem is not found until day 5 of regression testing, 15 man-days (120 work hours) after code was written.',1,'3','5',null,NOW(),null,'manual','active');

INSERT INTO `dmat`.`questionsmaster` (`question`,`issubjective`, `devopscategoryid`, `displaycategoryid`, `comments`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('How satisfied are you with your job?',0,'5','5',null,NOW(),null,'manual','active');


	/* Evaluations Master DATABASE*/
INSERT INTO `dmat`.`evaluationsmaster` (`lowerrange`, `upperrange`, `maturitylevel`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('0', '30', '1', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`evaluationsmaster` (`lowerrange`, `upperrange`, `maturitylevel`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('31', '55', '2', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`evaluationsmaster` (`lowerrange`, `upperrange`, `maturitylevel`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('56', '80', '3', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`evaluationsmaster` (`lowerrange`, `upperrange`, `maturitylevel`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('81', '95', '4', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`evaluationsmaster` (`lowerrange`, `upperrange`, `maturitylevel`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('96', '100', '5', NOW(), null, 'manual', 'active');



	/* Levels Recommendations Master DATABASE*/
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel` ,`maximumlevel` ,`devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('1', '2', '5', '1', 'Progressively look at moving the following components into version control -> application source code & configuration files -> Test scripts->Infrastructure related scripts -> All remaining files used to build, test, configure, deploy, run and document the service.# New work to be kept in separate branches and merged atleast bi-weekly.# Build to be triggered manually at frequent intervals.', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel`,`maximumlevel` , `devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('2', '3','5', '1', 'Progressively look at moving the following components into version control -> application source code & configuration files -> Test scripts->Infrastructure related scripts -> All remaining files used to build, test, configure, deploy, run and document the service.# New work to be kept in separate branches and merged atleast weekly.# Build to be compiled automatically on a scheduled basis, such as daily or nightly.', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel`,`maximumlevel` , `devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('3', '4','5', '1', 'Progressively look at moving the following components into version control -> application source code & configuration files -> Test scripts->Infrastructure related scripts -> All remaining files used to build, test, configure, deploy, run and document the service.# Branches to be created on a temporary basis and merged to master atleast on a daily basis.# When build is triggered, automated tests to be run and changes to be deployed to pre-prod, and on approval queued for production.', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel`,`maximumlevel` , `devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('4', '5','5', '1', 'Progressively look at moving the following components into version control -> application source code & configuration files -> Test scripts->Infrastructure related scripts -> All remaining files used to build, test, configure, deploy, run and document the service.# Branches to live for a few days max and all changes to be commited to master or trunk on a daily basis per developer. ', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel`,`maximumlevel` , `devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('5', '5', '5','1', 'You are mature in the Continual Integration aspect of the DevOps Journey.', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel`,`maximumlevel` , `devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('1', '2','5', '2', 'Unit tests to be automated at developers discretion. Also overall testing should validate conformance to requirements.# Security to be tested before a major release.', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel`,`maximumlevel` , `devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('2', '3','5', '2', 'UI specific tests to be automated and run prior to release. Also overall testing should cover most used functionality, data, code paths and configurations, with coverage measured against them.# Security to be tested before any  production update.', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel`,`maximumlevel` , `devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('3', '4','5', '2', 'Automated tests to be delivered and run as part of Definition of Done in the continuous integration and continuous delivery flow.# Security tests to be run In the continuous integration/delivery pipeline.', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel`,`maximumlevel` , `devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('4', '5','5', '2', 'End to end testing to be automated. Also overall testing should promote continuous improvement in user satisfaction, quality of service, and performance on business objectives.# Security checks to be integrated into the code review and security testing to be done before each commit.', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel`,`maximumlevel` , `devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('5', '5','5', '2', 'You are mature in the Continual Testing aspect of the DevOps Journey.', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel`,`maximumlevel` , `devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('1', '2','5', '3', 'Basic communication to be established for the team. Mistakes to be used as an opportunity to learn.# Product delivery performance reports to be used at the end of releases for identifying improvement opportunities.', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel`,`maximumlevel` , `devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('2', '3', '5','3', 'Team to be thoroughly informed about anything that affect the team goals. Collaboration to be encouraged.# Product engineering and service delivery peformance reports to be used periodically (end-of sprint, monthly, etc) for identifying improvement opportunities.', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel`,`maximumlevel` , `devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('3', '4','5', '3', 'Team to maintain transparent communication and collaborate constructively to ensure that the end goal is achieved . Innovative ideas to be actively shared.# Along with Product engineering and service delivery performance reports , operational performance reports also to be used for identifying improvement opportunities.', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel`,`maximumlevel` , `devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('4', '5','5', '3', 'Learning culture to be enabled within the team and organization. Experimentation, RCA\'s and skill/knowledge enhancement to be encouraged.# Metrics to be monitored at all levels including code, application, security as well as infrastructure and and displayed  publically.Metrics analysis to be incorporated as a regular activity in daily work and used to anticipate problems and achieve project goals.', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel`,`maximumlevel` , `devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('5', '5','5', '3', 'You are mature in the  Continual Learning aspect of the DevOps Journey.', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel`,`maximumlevel` , `devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('1', '2','5', '4', 'Environments to be managed manually using run books.# Progressively improve on the following aspects > Every team as a part of the project to be responsible for security in design, development and pipeline-> Teams to also ensure that customer information security people are a part of the demos(sprint review)->Security scanning to be built into the release pipeline.# Code to be deployed into production on a weekly/monthly basis.', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel`,`maximumlevel` , `devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('2', '3','5', '4', 'Final deployment to be automated from  build server to test environment to production.# Progressively improve on the following aspects > Every team as a part of the project to be responsible for security in design, development and pipeline-> Teams to also ensure that customer information security people are a part of the demos(sprint review)->Security scanning to be built into the release pipeline.# Code to be deployed into production on a daily/weekly basis.', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel`,`maximumlevel` , `devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('3', '4','5', '4', 'Every deployment to be automated and traceable to configurations, builds, code commit history, test history, work tracking and live site incidents.# Progressively improve on the following aspects > Every team as a part of the project to be responsible for security in design, development and pipeline-> Teams to also ensure that customer information security people are a part of the demos(sprint review)->Security scanning to be built into the release pipeline.# Code to be deployed into production on a hourly/daily basis.', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel`,`maximumlevel` , `devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('4', '5','5', '4', 'Automated release pipeline to provision environments as needed and ensure that they are destroyed when no longer in use. Containers, IaC or PaaS to be used.Have stages for progressively harsher testing.Use metrics to measure differences from the last deployment.# Progressively improve on the following aspects > Every team as a part of the project to be responsible for security in design, development and pipeline-> Teams to also ensure that customer information security people are a part of the demos(sprint review)->Security scanning to be built into the release pipeline.# Code to be deployed into production on demand.', NOW(), null, 'manual', 'active');
INSERT INTO `dmat`.`levelsrecommendationsmaster` (`currentlevel`, `recommendedlevel`,`maximumlevel` , `devopscategoryid`, `recommendations`, `creationdatetime`, `modificationdatetime`, `creationmode`, `status`) VALUES ('5', '5','5', '4', 'You are mature in the Continual Deployment aspect of the DevOps Journey.', NOW(), null, 'manual', 'active');	
	/* Options Master DATABASE*/
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES('By feature completion against spec',2,NOW(),'manual',1,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('In timeboxes such as sprints',3,NOW(),'manual',1,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We strive for a one-piece flow of product backlog items, stack-ranked, and delivered continuously',4,NOW(),'manual',1,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We create measurable experiments from hypotheses and use production data to assess results',5,NOW(),'manual',1,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',1,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('A product owner or manager decides the stack rank of our product backlog items',2,NOW(),'manual',2,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('A product owner or manager rates business importance for each product backlog items',3,NOW(),'manual',2,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('The stakeholders and the team regularly set business KPIs and the team reports on a regular cadence against the KPIs.',4,NOW(),'manual',2,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We instrument our software to measure the KPIs, plan work against them and report on a regular cadence',5,NOW(),'manual',2,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',2,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We do them when we think they are necessary',2,NOW(),'manual',3,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We budget a certain amount for engineering improvements',3,NOW(),'manual',3,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We periodically set KPIs for engineering and derive the needed work plans accordingly',4,NOW(),'manual',3,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Engineering improvements are ranked on the backlog just like feature work, bugs and all other items',5,NOW(),'manual',3,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',3,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('When a manager or product owner approves tasks or stories, we begin work on them immediately',2,NOW(),'manual',4,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We prioritize the backlog and only work on the highest-priority items. We begin only the items we can fit into a stated timebox or iteration, based on highest priority.',3,NOW(),'manual',4,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We use a Kanban board with WIP limits to minimize task switching and relieve individual overburdening, allowing focus on and improve speed of delivery & maximize time on task for the highest priority items',4,NOW(),'manual',4,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We use cycle time and flow efficiency (work time/idle time rations) measures to improve the flow of customer value through a system/value stream',5,NOW(),'manual',4,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',4,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We track dependencies in spreadsheets, project plans and through verbal/email communications',2,NOW(),'manual',5,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We track dependencies in our team Kanban boards',3,NOW(),'manual',5,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We discuss and plan for dependencies across teams in our department on a regular cadence',4,NOW(),'manual',5,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We tune our organizational structure to avoid as many dependencies as possible',5,NOW(),'manual',5,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',5,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We negotiate fixed price and fixed date contracts',2,NOW(),'manual',6,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We pay time and materials',3,NOW(),'manual',6,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We use the scope of work to estimate initially and adjust the estimates accordingly',4,NOW(),'manual',6,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We work on a basis of establishing trust and frequently reviewing outcomes as a basis for renewal. The supplier only produces value to the customer based on the mutually managed backlogs',5,NOW(),'manual',6,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above/ We donot have any suppliers for outsourced development',1,NOW(),'manual',6,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Whoever needs to deploy or troubleshoot',2,NOW(),'manual',7,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Only operations can access production',3,NOW(),'manual',7,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Developers can access production for with time-limited tokens',4,NOW(),'manual',7,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Production access is limited to automated processes and tokens that last a few hours',5,NOW(),'manual',7,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',7,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Team members have elaborated user stories',2,NOW(),'manual',8,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Team members work with product manager to understand features in the product backlog and identify & groom the user stories',3,NOW(),'manual',8,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Team members work with product manager to understand features in the product backlog, understand the impact of the same on business priorities, elaborate the features in the user-stories, groom them and identify its inter linkages.',4,NOW(),'manual',8,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Team members work with product owner, product management to understand product concept & functional architecture. They have comprehensive understanding of modules, workflow, features and its inter-dependencies. Team members define user stories of the features identified for the release, prioritize them based on value and inter-dependencies and groom them for engineering. ',5,NOW(),'manual',8,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',8,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('QA department tests all new builds and provides sign-off for the release',2,NOW(),'manual',9,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Responsible manager(s) must sign off and accept responsibility for every release',3,NOW(),'manual',9,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('A deployment is triggered by a human but executed by automation. An automated release pipeline ensures that only tested & clean code can be deployed',4,NOW(),'manual',9,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Anyone can initiate a release; deployment will gradually be exposed to increasing amounts of production traffic and if there is a problem, it will be remediated',5,NOW(),'manual',9,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',9,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Production incidents are handled by operations staff/L1-L2 teams. Root cause analysis is done for such incidents. In case operations staff/L1-L2 teams are unable to restore service, then an escalation process may be started on an exception basis to engage developers.',2,NOW(),'manual',10,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Developers and Ops do a joint retrospective to review the root cause of an issue once it\'s resolved. They plan how to prevent a recurrence',3,NOW(),'manual',10,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('They collaborate in real time, in a physical team room/war room or online chat room, IRC, IM, or other messaging channel',4,NOW(),'manual',10,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Developers rotate on-call duty and, when on duty, are paged to participate without delay in troubleshooting live site incidents related to their area of code',5,NOW(),'manual',10,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of them',1,NOW(),'manual',10,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Our process changes when management decides to make the change',2,NOW(),'manual',11,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We use regular retrospectives to identify impediments',3,NOW(),'manual',11,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Process improvement items are scheduled on the backlog with all other work',4,NOW(),'manual',11,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We conduct root-cause analysis on every production incident and identify the work needed to prevent recurrence',5,NOW(),'manual',11,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',11,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('There is a central team (either at customer side or at Persistent\'s side) responsible for enforcing security',2,NOW(),'manual',12,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Every team as a part of the project is responsible for security in design, development and pipeline and we have dedicated security coaches who train teams regularly',3,NOW(),'manual',12,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ("There is a central security team (either at customer side or at Persistent's side) automates scanning of everything before release to production",4,NOW(),'manual',12,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We build security scanning into the release pipeline',5,NOW(),'manual',12,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above/ Not Applicable.',1,NOW(),'manual',12,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Using open source components requires legal review and management approval .',2,NOW(),'manual',13,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We have identified a central package store of approved open source components',3,NOW(),'manual',13,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We automatically scan open source components for vulnerabilities and IP before taking a dependency on them',4,NOW(),'manual',13,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Our release pipeline automatically scans OSS component versions before every deployment and we remediate any newly discovered vulnerabilities',5,NOW(),'manual',13,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',13,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('The person doing the work decides if work is complete',2,NOW(),'manual',14,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Done means a potentially shippable increment is available at the end of a timebox',3,NOW(),'manual',14,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Done means software is deployed in production, available to real users',4,NOW(),'manual',14,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Done means we are collecting real-time metrics on quality of product/service provided by you and usage against new deployments to real users',5,NOW(),'manual',14,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We donot have a Definition of Done',1,NOW(),'manual',14,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('The team and customer have a detailed checklist which determines whether a story is "Ready Ready" to be taken into the sprint.Only in case all checklist items are ticked can a story can be taken into sprint',2,NOW(),'manual',15,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('The team and customer have identified some requirements(NFR, UX, Security etc) that need to be present in the user story to ensure that the user story can be taken into the sprint',3,NOW(),'manual',15,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('The team and customer have a detailed checklist which determines whether a story is "Ready Ready" to be taken into the sprint. Only in case all checklist items are ticked can a story can be taken into sprint. Also, during any sprint ceremonies if we find any misses we add that to the checklist as a continuous process',4,NOW(),'manual',15,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('The team and customer identify the stories which are ready to be taken into the sprint',5,NOW(),'manual',15,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We donot have a Definition of Ready',1,NOW(),'manual',15,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Both Application source code & configuration files',2,NOW(),'manual',16,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('All tests scripts along with source code and configuration files',3,NOW(),'manual',16,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Infrastructure related scripts , all tests scripts, configuration files and source code',4,NOW(),'manual',16,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('All files used to build, test, configure, deploy, run and document our service ',5,NOW(),'manual',16,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above/ Only source code',1,NOW(),'manual',16,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We have no branches and develop only in the trunk or master',2,NOW(),'manual',17,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We keep new work in separate branches and merge only when finished, usually in weeks or months',3,NOW(),'manual',17,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We keep traceability on code changes but treat branches as temporary by using topic branches that we squash-merge to master when the work is complete',4,NOW(),'manual',17,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We use branches that live for a few days max and commit all changes to the master or trunk at least daily',5,NOW(),'manual',17,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',17,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We review code changes infrequently',2,NOW(),'manual',18,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Some code is reviewed and we capture the review history using a pull request workflow or the equivalent',3,NOW(),'manual',18,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We do live peer reviews or pair programming',4,NOW(),'manual',18,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We make sure all code changes are peer-reviewed by the respective indivduals without it being allocated to people before being committed to the master or trunk',5,NOW(),'manual',18,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',18,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We track them in a spreadsheet or document',2,NOW(),'manual',19,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We use a work item tracking system',3,NOW(),'manual',19,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We keep versioned interfaces between our different services and services are automatically tested against the client contracts. Pull requests or commits of code violating the tests are rejected to prevent breaking the interface',4,NOW(),'manual',19,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We maintain an artefact repository (Nugget, Nexus, Artifactory, etc.) with the latest binaries and all teams pull from there. Our services are built to cope with downstream failure and we support multiple versions',5,NOW(),'manual',19,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',19,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Builds are created manually as needed',2,NOW(),'manual',20,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('A build is compiled automatically on a scheduled basis, such as daily or nightly',3,NOW(),'manual',20,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('A build is triggered, automated tests are run, the changes are deployed to pre-prod, and on approval queued to production',4,NOW(),'manual',20,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('A build is triggered, automated tests are run, and the changes are deployed with progressive exposure control and metrics to measure differences from the last deployment',5,NOW(),'manual',20,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',20,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We use manual runbooks and we can inspect the target environments and determine what is on them',2,NOW(),'manual',21,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Automated deployment from build server to test environment to production',3,NOW(),'manual',21,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Every deployment is automated and traceable to configurations, builds, code commit history, test history, work tracking and live site incidents',4,NOW(),'manual',21,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('An automated release pipeline provisions environments as needed and destroys them when no longer in use, using containers, IaC or PaaS, and provides with stages for progressively harsher testing',5,NOW(),'manual',21,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',21,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We deploy when the appropriate manager approves',2,NOW(),'manual',22,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We run a full test suite in a production-realistic environment and then deploy',3,NOW(),'manual',22,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('All gets deployed continuously but we use feature flags to control which end users have access to new features in production',4,NOW(),'manual',22,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We use progressive deployment with feature flags or exposure control and watch metrics to determine whether to continue rollout',5,NOW(),'manual',22,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',22,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We don\'t allow use of the public cloud',2,NOW(),'manual',23,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Teams are free to decide on their own to run their virtual machines',3,NOW(),'manual',23,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We allow use of the cloud (IaaS, PaaS & SaaS), as long as corporate data is secure',4,NOW(),'manual',23,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We strive for the best security, end-user experience and quality of service in a cloud-native manner',5,NOW(),'manual',23,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',23,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('They are managed by Operations',2,NOW(),'manual',24,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We rotate them when we need to and keep track of them in a versioned way',3,NOW(),'manual',24,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Most of them are kept in an encrypted repository',4,NOW(),'manual',24,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We scan code and all other files to make sure they are stored outside of the repository',5,NOW(),'manual',24,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',24,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Unit tests at the developer\'s discretion',0,NOW(),'manual',25,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Along with unit tests, pre-release tests from the user interface',3,NOW(),'manual',25,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Automated tests are delivered with code and must run green as part of our Definition of Done',4,NOW(),'manual',25,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Automation is run with every pull request prior to commit to the master branch and continuous integration (CI). Further automated preproduction tests are run after CI before deployment.',5,NOW(),'manual',25,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of them',-1,NOW(),'manual',25,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We avoid technical debt at all costs by architectural design and review',2,NOW(),'manual',26,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We periodically launch projects to refactor/replace/modernize major legacy systems',3,NOW(),'manual',26,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We list technical debt remediation work in our backlog prioritized by value, pain or impact',4,NOW(),'manual',26,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We incur short-term technical debt strategically to enable experimentation and fast feedback; we track and measure this debt and pay it off promptly once the experiment is complete',5,NOW(),'manual',26,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',26,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Testing that validates conformance to requirements and fixes of identified bugs',2,NOW(),'manual',27,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Testing that covers most used functionality, data, code paths and configurations, with coverage measured against them',3,NOW(),'manual',27,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Testing that is fast enough and thorough enough to provide feedback in the continuous integration and continuous delivery flow',4,NOW(),'manual',27,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Testing that promotes continuous improvement in user satisfaction, quality of service, and performance on business objectives',5,NOW(),'manual',27,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',27,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Before a major release',2,NOW(),'manual',28,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Before any production update',3,NOW(),'manual',28,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Security tests are run In the continuous integration and continuous delivery pipeline',4,NOW(),'manual',28,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('As part of the pull request and code review flow before code is committed',5,NOW(),'manual',28,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above/Not Applicable',1,NOW(),'manual',28,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We test manually when we can',2,NOW(),'manual',29,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We have automated tests to ensure new release works on different form factors',3,NOW(),'manual',29,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We test against a device matrix or cloud to validate on physical devices across all the necessary form factors',4,NOW(),'manual',29,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We integrate cross-device testing into our release pipeline so that every release is validated against all form factors we expect before being pushed',5,NOW(),'manual',29,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above/ We donot have mobile apps',1,NOW(),'manual',29,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Availability monitoring via pinging or synthetic transactions',2,NOW(),'manual',30,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Performance monitoring of the servers and infrastructure',3,NOW(),'manual',30,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Real user monitoring',4,NOW(),'manual',30,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Multi-tier views of end-to-end transactions including processing and network combined',5,NOW(),'manual',30,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',30,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('All decisions are made by leadership/management',2,NOW(),'manual',31,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We get to make decisions, but management support for the resulting issues is spotty',3,NOW(),'manual',31,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Leadership has provided mechanisms by which to make low to medium-impact decisions in a safe way',4,NOW(),'manual',31,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Leadership sets guardrails and communication mechanisms for safe decision-making. Guardrails are reviewed regularly to ensure they continue to foster autonomy and safety',5,NOW(),'manual',31,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',31,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We keep to ourselves to avoid being blamed for failure. Risk-taking is discouraged',2,NOW(),'manual',32,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('There is some communication. When mistakes are made, there is justice for the responsible person',3,NOW(),'manual',32,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Communication and collaboration is good among teams. Sharing innovative ideas is encouraged',4,NOW(),'manual',32,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('There is high cooperation among teams. Risks are shared. Failure leads to learning and inquiry to help the team improve. Innovation is encouraged and implemented',5,NOW(),'manual',32,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',32,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Non-compliant projects are shut down by the corporate governance body',2,NOW(),'manual',33,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('The corporate governance body will negotiate with the business unit to replace a non-compliant project',3,NOW(),'manual',33,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('All projects are monitored by the customer corporate governance body to learn from the initiatives that arise spontaneously',4,NOW(),'manual',33,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('The corporate governance body encourages innovation and will work together with/ensure that new projects are secure and that they fit corporate policy (either by adjusting policy based on new insights, or by changing implementation to adhere to policy',5,NOW(),'manual',33,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',33,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Failures are considered taboo. It\'s not discussed openly',2,NOW(),'manual',34,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('People are being told to avoid failure and plan for multiple contingencies',3,NOW(),'manual',34,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Failures are studied, analyzed and controls are enhanced based on failures',4,NOW(),'manual',34,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Leadership drives away \'fear of failure\'. Active experimentation and risk taking is encouraged',5,NOW(),'manual',34,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',34,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We hire knowledgeable employees with significant experience hence such investment is minimal',2,NOW(),'manual',35,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Employees are encouraged to learn on their own thru MOOC programs, meet-ups, internal learning forums, etc.',3,NOW(),'manual',35,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Employees have been given developmental goals. Organization reimburse investment made by employees',4,NOW(),'manual',35,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Organization has established competencies framework for all levels. These are must and integral to critical competencies',5,NOW(),'manual',35,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',35,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Based on code reviews',2,NOW(),'manual',36,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Based on bugs found',3,NOW(),'manual',36,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Pre-production code profiling, static code analysis or unit testing/code coverage',4,NOW(),'manual',36,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('We track the density of production incidents and performance back to the code',5,NOW(),'manual',36,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',36,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Feature requests and bug reports inform the teams decisions about the product backlog',2,NOW(),'manual',37,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Marketing campaigns track usage to understand response and conversion rates',3,NOW(),'manual',37,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Usage metrics informs the next steps in the product backlog',4,NOW(),'manual',37,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Usage metrics, A/B test results, and performance data are collected continuously and inform the next experiments that are run in every release',5,NOW(),'manual',37,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',37,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Manual testing, user acceptance testing or general acceptance criteria',2,NOW(),'manual',38,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Direct email / phone / web contact form, web meetings, or chat room',3,NOW(),'manual',38,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('In-product qualitative feedback (e.g. Send-a-Smile) and survey such as Net Promoter Score (NPS) are sent to the end users to guage the same.',4,NOW(),'manual',38,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Usage metrics are gathered with real user monitoring at 100% sampling',5,NOW(),'manual',38,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',38,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Based on the user acceptance testing and user adoption rate',2,NOW(),'manual',39,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Numbers of requests (calls, chat, tickets) received from end-user at Help-desk ',3,NOW(),'manual',39,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Incidents, problems and change requests logged by end-users within first 30 days of production launch',4,NOW(),'manual',39,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Continuous health monitoring of key processes and infrastcture performances thru utilities',5,NOW(),'manual',39,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',39,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Product delivery performance reports are used at the end of releases',2,NOW(),'manual',40,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Product engineering and service delivery peformance reports are used periodically (end-of sprint, monthly, etc)',3,NOW(),'manual',40,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Product engineering, services delivery and operational performance reports are used periodically',4,NOW(),'manual',40,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Metrics of product development, service delivery, operations and business performance are captured online and displayed  publically',5,NOW(),'manual',40,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('None of the above',1,NOW(),'manual',40,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Less often than once per six months',1,NOW(),'manual',41,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Between once per month and once every 6 months',2,NOW(),'manual',41,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Between once per week and once per month',3,NOW(),'manual',41,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Between once per day and once per week',4,NOW(),'manual',41,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Between once per hour and once per day',5,NOW(),'manual',41,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('On demand (multiple deploys per day)',6,NOW(),'manual',41,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('More than six months',1,NOW(),'manual',42,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Between one month and six months',2,NOW(),'manual',42,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Between one week and one month',3,NOW(),'manual',42,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Between one day and one week',4,NOW(),'manual',42,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Less than one day',5,NOW(),'manual',42,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Less than one hour',6,NOW(),'manual',42,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('More than six months',1,NOW(),'manual',43,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Between one month and six months',2,NOW(),'manual',43,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Between one week and one month',3,NOW(),'manual',43,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Between one day and one week',4,NOW(),'manual',43,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Less than one day',5,NOW(),'manual',43,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Less than one hour',6,NOW(),'manual',43,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('76%-100%',1,NOW(),'manual',44,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('61%-75%',2,NOW(),'manual',44,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('46%-60%',3,NOW(),'manual',44,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('31%-45%',4,NOW(),'manual',44,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('16%-30%',5,NOW(),'manual',44,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('0%-15%',6,NOW(),'manual',44,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Best Case (min) _ work days',0,NOW(),'manual',45,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('On an average _ work days',0,NOW(),'manual',45,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Worst Case (max) _ work days',0,NOW(),'manual',45,'active'); 

INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Best Case (min) _ work days',0,NOW(),'manual',46,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('On an average _ work days',0,NOW(),'manual',46,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Worst Case (max) _ work days',0,NOW(),'manual',46,'active'); 

INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Best Case (min) _ work days',0,NOW(),'manual',47,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('On an average _ work days',0,NOW(),'manual',47,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Worst Case (max) _ work days',0,NOW(),'manual',47,'active');

INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Best Case (min) _ work days',0,NOW(),'manual',48,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('On an average _ work days',0,NOW(),'manual',48,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('Worst Case (max) _ work days',0,NOW(),'manual',48,'active');

INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('1',0,NOW(),'manual',49,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('2',0,NOW(),'manual',49,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('3',0,NOW(),'manual',49,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('4',0,NOW(),'manual',49,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('5',0,NOW(),'manual',49,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('6',0,NOW(),'manual',49,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('7',0,NOW(),'manual',49,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('8',0,NOW(),'manual',49,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('9',0,NOW(),'manual',49,'active'); 
INSERT INTO `dmat`.`optionsmaster` (`optionname`, `score`, `creationdatetime`, `creationmode`, `questionid`, `status`) VALUES ('10',0,NOW(),'manual',49,'active');